guestbook/urls.py
from cgitb import html
from django.contrib import admin
from django.urls import path, include
from web.views import *
from django.urls import path
from django.views.generic import RedirectView
from web.views import *
from upload_img.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base),
    path('accounts/', include('django.contrib.auth.urls')),
    path('base/', base),
    path('about/', about),
    path('contact/', contact),
    # path('', RedirectView.as_view(url='message/')),
    #path('message/', MessageList.as_view()),
    path('message/', home),  # 改成新的 view function
    path('message/<int:pk>/', MessageDetail.as_view()), 
    path('message/create/', MessageCreate.as_view()),
    path('process/', image_upload_method), # 圖片上傳
    
    # 127.0.0.1/show/Test
    # => django 會透過 image_output 去找 title 是 Test 的照片
    path('show/<str:title>', image_output),  

]

web/urls.py
from django.urls import path
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('', RedirectView.as_view(url='message/')),
    #path('message/', MessageList.as_view()),
    path('message/', home),  # 改成新的 view function
    path('message/<int:pk>/', MessageDetail.as_view()), 
    path('message/create/', MessageCreate.as_view()),  
]

upload_img/models.py
from django.db import models

class upload_img(models.Model):
    img_title = models.CharField(max_length=200)
    img_path = models.ImageField(upload_to = "static/upload_img") #--> 關鍵
    img_process_path = models.CharField(max_length=200, null=True)


web/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    user = models.CharField("姓名", max_length=50)
    subject = models.CharField("主旨", max_length=200)
    content = models.TextField("內容")
    publication_date = models.DateTimeField("留言日期", auto_now_add=True)

    def __str__(self):
        return self.subject

        

upload_img/forms.py
from django import forms
from upload_img.models import upload_img

class ImageFileUploadForm(forms.ModelForm):
    class Meta:
        model = upload_img
        fields = ('img_title', 'img_path',)
        
        # 改名
        labels = {
            'img_title': '檔案名稱',
            'img_path': '檔案位置',
        }

upload_img/views.py
from turtle import title
from django.shortcuts import render
from django.http import JsonResponse

from upload_img.models import upload_img
from .forms import ImageFileUploadForm

from django.contrib.sites.shortcuts import get_current_site
# import .web_api.alarm_file
# import test.models.
from upload_img.forms import ImageFileUploadForm
from django.http import JsonResponse

import subprocess, os

import argparse
import glob
import os


# 檔案上傳
def image_upload_method(request):
    if request.method == "POST":
        form = ImageFileUploadForm(request.POST, request.FILES)
        # call .py（呼叫 AI Model）
        subprocess.Popen([
        'python',
        'static/test/inference_realesrgan.py',
        # '-i',
        # 'static/test/X4',
        ])
        if form.is_valid():
            form.save()
            print(form.cleaned_data)
            image = form.cleaned_data.get('選擇檔案')
            print(image)
            name = form.cleaned_data.get('檔案名稱')
            print(name)
            return JsonResponse({'error':False, 'message': '上傳成功'})
        else:
            return JsonResponse({'error':True, 'errors': form.errors})
    else:
        form = ImageFileUploadForm()
        return render(request, 'process.html', {'form': form})

def image_output(request):
    img_outpath = upload_img.object.get(title = title) # 用 title 尋找上傳時填寫的id
    return render(request, 'show.html',locals())


# # call .py（呼叫 AI Model）
# subprocess.Popen([
#     'python',
#     'static/test/inference_realesrgan.py',
#     # '-i',
#     # 'static/test/X4',
# ])


web/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from .models import Message
from django.shortcuts import render, redirect
from django import forms

# 留言列表
class MessageList(ListView):
    model = Message
    ordering = ['-id']      # 以 id 欄位值由大至小反向排序

# 留言檢視
class MessageDetail(DetailView):
    model = Message
    fields = ['user', 'subject', 'content']  

# 新增留言
class MessageCreate(CreateView):
    model = Message
    fields = ['user', 'subject', 'content']     # 僅顯示 user, subject, content 這 3 個欄位
    success_url = '/message/'                   # 新增成功後，導向留言列表
    template_name = 'form.html'                 # 指定欲使用的頁面範本

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('user', 'subject', 'content')

def home(request):
    # 接收到資料的動作
    #   1. 存到資料庫
    #   2. 查詢"新"的留言內容
    if request.method == 'POST':
        form = MessageForm(request.POST)
        form.save()
        message_list = Message.objects.all().order_by('-publication_date')
        return render(request, 'book.html', locals())
    else:
    # "未"接收到資料的動作
    #   1. 建立表單
    #   2. 查詢資料庫中的資料
        form = MessageForm()
        message_list = Message.objects.all().order_by('-publication_date')
        return render(request, 'book.html', locals())


def base(request):
    return render(request, 'base.html', locals())

def process(request):
    return render(request, 'process.html', locals())

def about(request):
    return render(request, 'about.html', locals())

def contact(request):
    return render(request, 'contact.html', locals())



# def listone(request): 
#     try: 
#         unit = Message.objects.get(user = message.id) #讀取一筆資料
#     except:
#         errormessage = " (讀取錯誤!)"
#     return render(request, "contact.html", locals())

templates/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {%load static%}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Photo Retouch</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Photo Retouch</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/base">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/process">Process</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/message">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
         <!-- About-->
        <section class="page-section" id="about">
            <div class="container">
                <div class="text-center">
                    <h1 class="section-heading text-uppercase">About</h1>
                    <h3 class="section-subheadingg text-muted">專題研究呈現</h3>
                </div>
                <br><br><br>
                <ul class="timeline">
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/1.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>1. 摘要</h4>
                                <h4 class="subheading">Our Humble Beginnings</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/2.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>2. 文獻回顧</h4>
                                <h4 class="subheading">An Agency is Born</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/3.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>3. 研究方法</h4>
                                <h4 class="subheading">Transition to Full Service</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/4.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>4. 研究成果</h4>
                                <h4 class="subheading">Phase Two Expansion</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/3.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>5. 結論</h4>
                                <h4 class="subheading">Transition to Full Service</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="{% static 'assets/img/about/4.jpg' %}" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>6. 參考資料</h4>
                                <h4 class="subheading">Phase Two Expansion</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <h4>
                                Be Part
                                <br />
                                Of Our
                                <br />
                                Story!
                            </h4>
                        </div>
                    </li>
                </ul>
            </div>
        </section>
        <!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/1.jpg' %}" alt="..." />
                            <h4>蕭光肇</h4>
                            <br>
                            <p class="text-mutedd">Lead &nbsp;Designer</p>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/2.jpg' %}" alt="..." />
                            <h4>李冠嫆</h4>
                            <br>
                            <p class="text-mutedd">Lead &nbsp;Marketer</p>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/tsen.jpg' %}" alt="..." />
                            <h4>謝亞岑</h4>
                            <br>
                            <p class="text-mutedd">Lead &nbsp;Developer</p>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/2.jpg' %}" alt="..." />
                            <h4>林欣平</h4>
                            <br>
                            <p class="text-mutedd">Lead &nbsp;Developer</p>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="team-member">
                            <img class="mx-auto rounded-circle" src="{% static 'assets/img/team/3.jpg' %}" alt="..." />
                            <h4>吳長昇</h4>
                            <br>
                            <p class="text-mutedd">Lead &nbsp;Developer</p>
                    </div>
                    </div>
                </div>
                <br><br>
                <div class="text-center">
                    <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p></div>
                </div>
            </div>
        </section>
    
        <!-- Footer-->
        <footer class="bg-light py5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Photo Retouch 2022</div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/book.html
{% extends "book_darft.html" %}
{% block content %}       
            <!-- 留言輸入 -->
            <div>
                <form method='POST'>
                    {% csrf_token %}
                    <table>
                    {{ form.as_p }}
                    </table>
                    <input type="submit" value="送出" />
            </form>
            </div>
            <hr>
            <!-- Dispaly Message -->
            <div>
                {{ message_list }}
        
                <ul>
                    {% for message in message_list %}
                    <li>
                    {{ message.publication_date }}
                    <a href="{{ message.id }}">{{ message.subject }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
{% endblock %}

templates/book_darft.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {%load static%}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Photo Retouch</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Photo Retouch</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/base">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/process">Process</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/message">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <br><br><br><br><br><br><br>
        <div class="container">
            <h1>留言板</h1>      
            <hr>
            {% block content %} 


            {% endblock %} 
        </div>    
        <!-- Footer-->
        <footer class="bg-light py-2">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Photo Retouch 2022</div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/form.html
{% extends 'contact.html' %}

{% block content %}
<form action="" method="post">
 {% csrf_token %}
 <table>
   {{ form.as_table }}
 </table>
 <input type="submit" value="送出" />
</form>
{% endblock %}

templates/process.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {%load static%}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Photo Retouch</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Photo Retouch</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/base">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/process">Process</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/message">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <br><br><br><br><br><br><br>
       
        <div class="container">
            <h1>操作介面</h1>
            <br>
            <div>
                <form enctype="multipart/form-data" id="id_ajax_upload_form" method="POST" novalidate="">
                   {% csrf_token %}
                   {{ form.as_p }}
                  
                   <img id="upload_img" src="" />  <!-- 預覽 -->
                   <br>
                   <input type="submit" value = "開始"/>
                </form>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                <script type="text/javascript">
                 // form upload
                    $('#id_ajax_upload_form').submit(function(e){
                     e.preventDefault();
                     $form = $(this)
                     var formData = new FormData(this);
                     $.ajax({
                         url: window.location.pathname,
                         type: 'POST',
                         data: formData,
                         success: function (response) {
                             $('.error').remove();
                             console.log(response)
                             if(response.error){
                                 $.each(response.errors, function(name, error){
                                     error = '<small class="text-muted error">' + error + '</small>'
                                     $form.find('[name=' + name + ']').after(error);
                                 })
                             }
                             else{
                                 alert(response.message)
                                 window.location = ""
                             }
                         },
                         cache: false,
                         contentType: false,
                         processData: false
                     });
                 });

                 // 預覽
                 $('#id_img_path').on('change', function(e){      // "#id_img_path"：django內設路徑
                    const file = this.files[0]; //將上傳檔案轉換為base64字串
                        
                    const fr = new FileReader(); //建立FileReader物件
                    fr.onload = function (e) {
                       upload_img=$('#upload_img');
                       upload_img.attr('src', e.target.result); //讀取的结果放入圖片
                       upload_img.attr('width', 500); //設定寬度
                 };
                  
              // 使用 readAsDataURL 將圖片轉成 Base64
                 fr.readAsDataURL(file);
             });
             // end
                </script>
            </div>
        </div>    
        <!-- Footer-->
        <footer class="bg-light py-2">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Photo Retouch 2022</div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/web/message_detail.html
{% extends "book_darft.html" %}

{% block content %}
  <h2>姓名</h2>
  {{ message.user }}<BR>
  <h2>主旨</h2>
  {{ message.subject }}<BR>
  <h2>內容</h2>
  {{ message.content|linebreaks }}<BR>

  <nav>
    <button type="button" class="btn btn-primary" onClick="javascript:history.back()" style="color: #000000;">回上頁</button>
  </nav>
{% endblock %}

templates/web/message_list.html
{% extends 'base.html' %}

{% block content %}
<ul>
  {% for message in message_list %}
  <li>
    {{ message.publication_date }}
    <a href="{{ message.id }}">{{ message.subject }}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}